export const FETCH_DATA_GROUP_REQUEST = 'FETCH_DATA_GROUP_REQUEST'
export const FETCH_DATA_GROUP_SUCCESS = 'FETCH_DATA_GROUP_SUCCESS'
export const FETCH_DATA_GROUP_FAILED = 'FETCH_DATA_GROUP_FAILED'

export const ADD_DATA_GROUP_REQUEST = 'ADD_DATA_GROUP_REQUEST'
export const ADD_DATA_GROUP_SUCCESS = 'ADD_DATA_GROUP_SUCCESS'
export const ADD_DATA_GROUP_FAILED = 'ADD_DATA_GROUP_FAILED'

export const DELETE_DATA_GROUP_REQUEST = 'DELETE_DATA_GROUP_REQUEST'
export const DELETE_DATA_GROUP_SUCCESS = 'DELETE_DATA_GROUP_SUCCESS'
export const DELETE_DATA_GROUP_FAILED = 'DELETE_DATA_GROUP_FAILED'
